auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: ScienceBank
url: http://startupjing.github.io
feed: /atom.xml
author_info: <a href="http://startupjing.github.io/">startupjing</a>
