markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 12
paginate_path: page/:num

blog:
    name: Jing Lu
    description: My Blogs
    title: Science Bank
    url: http://startupjing.github.io/ 
author:
    # Profile links on the left sidebar, leave blank to ignore
    name: Jing Lu
    email: jinglu@wustl.edu  
    github: startupjing  
    linkedin: www.linkedin.com/in/jinglu111
    facebook: www.facebook.com/jing.lu.9615
    logo: http://chrispher.github.com/res/img/logo.png

